version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: appgym_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appgymdb
    ports:
      - "5432:5432"
    volumes:
      - appgym_pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  appgym_pgdata:
